<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="admin-PC" failures="0" tests="4" name="com.MyProjectStore.TestCase.TC_MyAccount" time="14.473" errors="1" timestamp="2023-12-22T19:29:57 IST" skipped="3">
  <testcase classname="com.MyProjectStore.TestCase.TC_MyAccount" name="LoginUsingDDT" time="14.473">
    <error message="Cannot invoke &quot;org.apache.poi.ss.usermodel.Workbook.getSheetAt(int)&quot; because &quot;com.MyProjectStore.Utility.ReadExcel.wb&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Workbook.getSheetAt(int)" because "com.MyProjectStore.Utility.ReadExcel.wb" is null
at com.MyProjectStore.Utility.ReadExcel.identifySheet(ReadExcel.java:26)
at com.MyProjectStore.Utility.Map.readDataToMap(Map.java:12)
at com.MyProjectStore.TestCase.TC_MyAccount.LoginUsingDDT(TC_MyAccount.java:144)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- LoginUsingDDT -->
  <system-out/>
  <testcase classname="com.MyProjectStore.TestCase.TC_MyAccount" name="VerifyRegisteration">
    <skipped/>
  </testcase> <!-- VerifyRegisteration -->
  <system-out/>
  <testcase classname="com.MyProjectStore.TestCase.TC_MyAccount" name="verifyLogin">
    <skipped/>
  </testcase> <!-- verifyLogin -->
  <system-out/>
  <testcase classname="com.MyProjectStore.TestCase.TC_MyAccount" name="productPurchase">
    <skipped/>
  </testcase> <!-- productPurchase -->
  <system-out/>
</testsuite> <!-- com.MyProjectStore.TestCase.TC_MyAccount -->
